### ISSUE TITLE
Type 'User' does not conform to protocol 'DefaultsSerializable'

### ISSUE THREAD

**Issue by GanZhiXiong** [sindresorhus/Defaults#110]
- Xcode 13.3
- macOS Monterey 12.3.1
- M1

![image](https://user-images.githubusercontent.com/27394631/188216861-0aead181-73ce-4416-91d3-a47a8d017881.png)

<img width="699" alt="image" src="https://user-images.githubusercontent.com/27394631/188217069-794c500d-b96f-4355-9eb5-cd802ac38354.png">

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/Defaults/blob/main/workaround.md

This is fixed in Xcode 14.

**Comment by GanZhiXiong** [comment]
Thank you, solved!
