### ISSUE TITLE
Tuples error: type 'User11' does not conform to protocol 'Decodable' and 'Encodable'

### ISSUE THREAD

**Issue by GanZhiXiong** [sindresorhus/Defaults#111]
```swift
struct User11: Codable, Defaults.Serializable {
	let name: String
	let age: String
	let languages: (String, String)
}
``` 

Can  support for Tuples? 
or can I set the languages in the above code to not write?

**Comment by sindresorhus** [comment]
This is not a problem with this package. If you remove `Defaults.Serializable`, it still fails. Tuples cannot conform to protocols, which is indeed an annoying Swift limitation.

https://www.objc.io/blog/2019/08/13/conforming-tuples-to-protocols/
