### ISSUE TITLE
class type update is invalid

### ISSUE THREAD

**Issue by GanZhiXiong** [sindresorhus/Defaults#117]
The code below `test41` update name and age is invalid, I don't know why?
``` swift
class GanUser2: Codable, Defaults.Serializable {
    var name: String
    var age: String

    init(name: String, age: String) {
        self.name = name
        self.age = age
    }
}

extension Defaults.Keys {
    static let ganUser2 = Key<GanUser2>("ganUser2", default: GanUser2(name: "a", age: "1"))
}

final class GanTests: XCTestCase {
    override func setUp() {
        super.setUp()
//		Defaults.removeAll()
    }

    override func tearDown() {
        super.tearDown()
//		Defaults.removeAll()
    }

    func test31() {
        print(Defaults[.ganUser2].name, Defaults[.ganUser2].age)
    }
    func test41() {
        Defaults[.ganUser2].name = "b"
        Defaults[.ganUser2].age = "2"
        print(Defaults[.ganUser2].name, Defaults[.ganUser2].age)
    }
}
```

**Comment by hank121314** [comment]
This is an expected behavior.
When `GanUser2` is a `class`, it will not trigger the [setter](https://github.com/sindresorhus/Defaults/blob/bc1af5d8728db4957ba3eac0f944362654247683/Sources/Defaults/Defaults.swift#L72), which means `UserDefaults` will not update by this instruction.
When `GanUser2` is a `struct`, the setter will be triggered and update the value in `UserDefaults`.

If you want to use `GanUser2` as a class, consider creating a new instance just like changing struct properties does.
ex.

```swift
Defaults[.ganUser2] =  GanUser2(name: "b", age: "2")
```

**Comment by GanZhiXiong** [comment]
@hank121314 
Thank you very much for your reply.
why class not support trigger the setter?

**Comment by hank121314** [comment]
It is in-depth swift compiler knowledge.
`Defaults` use a [subscription](https://github.com/sindresorhus/Defaults/blob/bc1af5d8728db4957ba3eac0f944362654247683/Sources/Defaults/Defaults.swift#L69) to access the `UserDefaults` storage with `Key`.
In swift, there are [multiple subscription access strategies](https://github.com/apple/swift/blob/50794e1ae31a08b492cc717ead6f99e7d6932e21/lib/SILGen/SILGenLValue.cpp#L2649-L2673) depending on the type of variable.
For `class`, the access strategy will be `DirectToAccessor`, which means it will only use a getter.
For `struct`, the access strategy will be `MaterializeToTemporary`, which means it will use both getter and setter.

**Comment by GanZhiXiong** [comment]
The reply was prompt and clear.
Thank you very much!
