### ISSUE TITLE
Is there a way to get an iterator over all the keys?

### ISSUE THREAD

**Issue by davidwernhart** [sindresorhus/Defaults#127]
I would love to computationally access all the keys via an iterator or array-like access. This would be very handy for saving backups of the defaults and modifying or migrating keys without always explicitly accessing them via Defaults[.name].

Thank you for your help and kind regards,
David

**Comment by sindresorhus** [comment]
There's no way to do this or even add it. Swift needs better reflection capabilities first.

However, you can access all the UserDefaults values using `UserDefaults.standard.dictionaryRepresentation()`.

**Comment by davidwernhart** [comment]
I see, that's really unfortunate.

Thank you anyways.
