### ISSUE TITLE
Using Defaults to share among multiple frameworks?

### ISSUE THREAD

**Issue by Maschina** [sindresorhus/Defaults#129]
Generic question: Is it feasible to use the `Defaults` framework to keep the UserDefaults data synched among the multiple frameworks that my app is currently relying on? I am currently using several frameworks to structure and maintain my code base. Thanks for your short view on this.

**Comment by sindresorhus** [comment]
I don't see any problem in doing that. They will all share the `UserDefaults.standard` suite under the hood. So technically there's no "syncing".
