### ISSUE TITLE
accentColor didn't work with Defaults

### ISSUE THREAD

**Issue by owenzhao** [sindresorhus/Defaults#139]
I set accent color to system orange in assets folder. And in code 

```swift
static let traceColor = Defaults.Key<Color>("traceColor", default: Color.orange) // works
static let traceColor = Defaults.Key<Color>("traceColor", default: Color.accentColor) // doesn't work
```

when reset the default key, 

```swift
Defaults.reset(.traceColor)
```

The accentColor set by reset is the system default blue instead my own setting orange. Any idea?

Defaults 7.2.0
Xcode 14.3.1 (14E300b) 
iOS 16.5

**Comment by sindresorhus** [comment]
I don't think there's much we can do about this other than documenting the behavior. `Color` is not directly serializable, so the serialization works by first converting to `UIColor`/`NSColor` and then using the native color serialization.

As a workaround, you could store `UIColor.tintColor` and then just wrap it in `Color()` where you use it.

**Comment by owenzhao** [comment]
```swift
static let traceColor = Defaults.Key<Color>("traceColor", default: Color(uiColor: .tintColor))
```

Suggested worked. Thank you and please add this to the document as a workaround.
