### ISSUE TITLE
Swift 5 upgrade process

### ISSUE THREAD

**Issue by OdNairy** [sindresorhus/Defaults#14]
Hi

I wanna to say few words about CocaoPods spec updates. Every time you change your .podspec to new values you have to increase version. In latest [changeset](https://github.com/sindresorhus/Defaults/commit/908d3b4ee17e4f7534750d55a0fa2e532ff4f18b#diff-744147f81603428deac92c88b8e32279) only swift version was changed. In this case no client of 1.0.0 (swift4.2) would get update through `pod update Defaults`. 
May you bump spec version as well, please?

**Comment by sindresorhus** [comment]
There's no CocoaPods spec update, because there's no new version. Look at the commit and Git tags. I didn't do a release as the Swift 5 upgrade didn't change any code. I plan to do a new release when #13 is merged.

**Comment by OdNairy** [comment]
Right, there is no update from codebase point of view. But podspec was changed so Pod version got update. 
I really like your library and use it on my work project. We are migrating to Swift 5 right now including all available dependencies. Right now to update Defaults we have to clear each CI node CocoaPods Cache to make it install new version of Defaults 1.0.0.

**Comment by sindresorhus** [comment]
> But podspec was changed so Pod version got update.

That is very surprising behavior, since I have to manually push the Pod (`pod trunk push`) when doing a new version. I assumed the pod spec would only update when I manually pushed with `pod trunk push`.

> I really like your library and use it on my work project.

Thanks for using it 🙌 Let me know if you have any requests or feedback.

---

Sidenote: If you're using the observation feature, we might want to take a look at https://github.com/sindresorhus/Defaults/pull/13 and see if you have any feedback.

**Comment by sindresorhus** [comment]
New release is out :)

```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  Defaults (2.0.0) successfully published
 📅  April 5th, 14:28
 🌎  https://cocoapods.org/pods/Defaults
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

**Comment by OdNairy** [comment]
Thanks for the fast release. And for an awesome Library :)
