### ISSUE TITLE
[Suggestion] Support for Cocoa Bindings

### ISSUE THREAD

**Issue by Ivorforce** [sindresorhus/Defaults#15]
... which is extremely useful for GUI. An "emulation" instead using kvc would also suffice for most purposes, I think.

**Comment by Ivorforce** [comment]
A rough implementation might look like this:

`    
extension NSObject {
    open func bind<Object, Source>(_ binding: NSBindingName, to observable: Object, withKey key: Defaults.Key<Source>, options: [NSBindingOption: Any] = [:], transform: ((Source) -> AnyObject?)? = nil, back: ((AnyObject?) -> Source)? = nil) {
        let ftransform: (String?) -> AnyObject? = { value in
            guard let value = value.map(decode) else {
                    return nil
            }
            
            return transform.map { $0(value) } ?? value as AnyObject
        }

        let fback: (AnyObject?) -> String? = { value in
            guard let value = (back.map { $0(value) } ?? (value as? Source)) else {
                return nil
            }
            
            return encode(value)
        }

        var options = options
        options[.valueTransformer] = SimpleTransformer<String, AnyObject>(there: ftransform, back: fback)

        bind(binding, to: observable, withKeyPath: key.name, options: options)
    }
}
`

Personally I like passing transformers directly but obviously this can be accomplished with a usual ValueTransformer as well.

**Comment by sindresorhus** [comment]
With SwiftUI and Combine, there's no future for legacy Cocoa bindings, so I'm not really interested in maintaining code for this.

Closing this in favor of #23.
