### ISSUE TITLE
High CPU and Hign Memory increase

### ISSUE THREAD

**Issue by averyhome** [sindresorhus/Defaults#154]
when i use like this

        .navigationDestination(isPresented: $isPushToHelp, destination: {
              SettingView()
        })

if  SettingView contains
     @Default(.hiddenAds) var hiddenAds
then the cup and memory will increase to the max

when i remove the  @Default(.hiddenAds) var hiddenAds 
it will be ok
please how can i resolve it

**Comment by sindresorhus** [comment]
Duplicate of #146

**Comment by averyhome** [comment]
> Duplicate of #146
oops， but i can not find any solution in #146 
or i need update the Defaults version?
