### ISSUE TITLE
Optional Keys crash Xcode 16

### ISSUE THREAD

**Issue by ConfusedVorlon** [sindresorhus/Defaults#177]
It seems that optional keys are not caught by

			if (defaultValue as? _DefaultsOptionalProtocol)?._defaults_isNil == true {
				return
			}
			
The good news is that this is caught in the tests...

**Comment by ConfusedVorlon** [comment]
XCode 15.4 defines ExpressibleByNilLiteral

Conforming Types
[Optional]

XCode 16 states:

[Optional]
Conforms when Wrapped conforms to Escapable.

meanwhile, Escapable seems to have no requirements, but not to be available without 

  -enable-experimental-feature NonescapableTypes
  
 If I do enable that feature, then compilation fails with a circular reference as soon as I include a key

**Comment by hank121314** [comment]
It seems to be the same as this issue: https://github.com/apple/swift/issues/74282

**Comment by ConfusedVorlon** [comment]
Brilliant - thank you.

**Comment by ConfusedVorlon** [comment]
fyi - not fixed on beta 2

**Comment by ConfusedVorlon** [comment]
Fixed in Beta 3 :)
