### ISSUE TITLE
My  Defaults.Key is dynamically created, how to use the @Default syntax. 

### ISSUE THREAD

**Issue by JRJian** [sindresorhus/Defaults#179]
`let selectedCalendarIDs = Defaults.Key<[String]>("\(widget.id)_selectedCalendarIDs", default: [])`

How to use my create key?
`@Default(？？？？) var selectedCalendarIDs`

**Comment by sindresorhus** [comment]
Same as how you would create a `@State` dynamically, you assign the underscored storage (for example, `self._someKeyName`) in your initializer.

**Comment by JRJian** [comment]
Thanks, got it!
