### ISSUE TITLE
The Cocoapods package is outdated

### ISSUE THREAD

**Issue by ShlomoCode** [sindresorhus/Defaults#188]
It seems the Cocoapods version (https://cocoapods.org/pods/Defaults) is stuck on v4.2.0.
Even when I tried to use a newer syntax like `Defaults.updates` I got an error `Type 'Defaults' has no member 'updates'`.
Could you please publish a new version to Cocoapods?
Thanks!

**Comment by sindresorhus** [comment]
Defaults has not supported CocoaPods for a long time. You'll have to move to using the SPM version. Make sure to read release notes for each major version.

**Comment by ShlomoCode** [comment]
Does it require in-code support? Isn't it just publishing a new version?
