### ISSUE TITLE
Package Resolution Failed in Xcode 11

### ISSUE THREAD

**Issue by emorydunn** [sindresorhus/Defaults#19]
I attempted to add Defaults through Xcode's new SPM support, but hit an error:

Source files for target Defaults should be located under 'Sources/Defaults', or a custom sources path can be set with the 'path' property in Package.swift

It looks like Xcode isn't happy that the source files are directly in `Sources` rather than nested.

**Comment by magnusburton** [comment]
This seems to be broken once again. Im on Xcode 16.1 and tried both Defaults v9.0.0 and using main branch in SPM.
