### ISSUE TITLE
I was using enum without Codable and it worked with 7.3.1, then I decided to upgrade to 8.2.0.

### ISSUE THREAD

**Issue by owenzhao** [sindresorhus/Defaults#192]
Something like this: 

```swift
static let mainViewStyle = Key<MainViewStyle>("mainViewStyle", default: .concentrationFirst)

enum MainViewStyle: Int, Defaults.Serializable, CaseIterable, Identifiable {
    var id: Self { self }
    
    case classic
    case concentrationFirst
    case timerFirst
}
```

It worked fine in 7.3.1. And it passed building after upgrading to 8.2.0. What I should I do next? Can I just live it there? Because I am afraid if I add Codable, the previous settings of this key will be set to default as the backend type may be changed. 

Any suggestions?

**Comment by sindresorhus** [comment]
What is the problem? It's not really clear from your description.

**Comment by owenzhao** [comment]
> What is the problem? It's not really clear from your description.

As in the [migration guide from 7.3.1 to 8.0.0](https://github.com/sindresorhus/Defaults/blob/3efef5a28ebdbbe922d4a2049493733ed14475a6/migration.md). You said that Codable must be use together with Defaults.Serializable. So I want to know if that is really a must. If that is a must, what should I do to convert my state to Codable to keep my previous values as this was not mentioned in the guide.

**Comment by sindresorhus** [comment]
That's the migration guide for v4 to v5. Codable has not been required for years.

**Comment by owenzhao** [comment]
> That's the migration guide for v4 to v5. Codable has not been required for years.

I see. So there is no migration needed from 7.3.1 to 8.0.0. Thanks.
