### ISSUE TITLE
Instance member 'subscript' cannot be used on type 'Defaults'

### ISSUE THREAD

**Issue by khacdat1994** [sindresorhus/Defaults#26]
how to use? error: "Instance member 'subscript' cannot be used on type 'Defaults'" when i call Defaults[.quality]

**Comment by sindresorhus** [comment]
v3 is already published on CocoaPods: https://github.com/CocoaPods/Specs/blob/master/Specs/0/a/a/Defaults/3.0.0/Defaults.podspec.json
