### ISSUE TITLE
SwiftUI support

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Defaults#28]
Would be nice to have something like the `@Published` property wrapper, but that also handles the synchronization of UserDefaults.

```swift
struct FooView: View {
	@Defaults.Published(.timeZonesInMenu) var arrayOfThings
}
```

**Comment by sindresorhus** [comment]
This is what I've currently come up with, but it requires accessing the value using `.value`. Would be nice to not have to do that.

```swift
private var defaultsObservableObservations = [DefaultsObservation]()
@available(macOS 10.15, *)
final class DefaultsObservable<Value: Codable>: ObservableObject {
    private var ignoreObservation = false
​
    let key: Defaults.Key<Value>
​
    @Published var value: Value {
        didSet {
            ignoreObservation = true
            Defaults[key] = value
            ignoreObservation = false
        }
    }
​
    init(_ key: Defaults.Key<Value>) {
        self.key = key
        self.value = key.defaultValue
​
        defaultsObservableObservations.append(Defaults.observe(key) { [weak self] change in
            guard self?.ignoreObservation == false else {
                return
            }
​
            self?.value = change.newValue
        })
    }
}
​
@available(macOS 10.15, *)
struct TimeZoneView: View {
    @ObservedObject var foo = DefaultsObservable(.someDefaultsKey)
}
```

Feedback wanted!

// @ThatsJustCheesy @Ybrin

**Comment by Ybrin** [comment]
I haven't had a chance to look into Swift UI yet. But I guess I will look through it in the next time. If I do I will definitely think about it.

**Comment by ThatsJustCheesy** [comment]
I'm in a similar position, I've just upgraded to 10.15 and so will have to play around with SwiftUI some more before I can understand your code :)

**Comment by m-a-v** [comment]
At the moment I'm still experimenting with the best way to store data in SwiftUI. So far I like the Defaults approach very much. Before I have used something similar like this here: https://github.com/kodelit/UserDefaultPropertyWrapper

Could you make a sample how to use the DefaultsObservable?
