### ISSUE TITLE
Add ability to subscribe to multiple keys or any change in a given suite

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Defaults#30]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2464%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/Defaults/issues/30)

This can be useful when you need to handle changes to multiple keys the same.

Should support optionally giving an array or keys or if not given subscribe to all changes.

Something like this:

```swift
Defaults.observeAll<T: Codable>(
	_ keys: Defaults.Key<T>,
	options: NSKeyValueObservingOptions = [.initial, .old, .new],
	handler: @escaping () -> Void
) -> DefaultsObservation

Defaults.observeAll<T: Codable>(
	suite: UserDefaults = .standard,
	options: NSKeyValueObservingOptions = [.initial, .old, .new],
	handler: @escaping () -> Void
) -> DefaultsObservation
```

They should include change objects.

It should also prevent infinite recursion if you call, for example, `Defaults[.foo] = true` inside the `handler` as that would normally emit an event, which would call it again infinitely. If it doesn't make sense as default, at least there should be an option for this.

The `suite:` overload would get all the keys in the given suite and listen to those events. It should **not** use `UserDefaults.didChangeNotification`.

I think it could be useful with an overload that listens to all keys defined in `Defaults.Keys`.

Feedback wanted.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $64.00)

- [<img src='https://avatars1.githubusercontent.com/u/170270?v=4' alt='sindresorhus' width=24 height=24> sindresorhus](https://issuehunt.io/u/sindresorhus) ($64.00)

### Submitted pull Requests
- [#49 Ability to subscribe to multiple keys or any change](https://issuehunt.io/r/sindresorhus/Defaults/pull/49)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/Defaults/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by fredyshox** [comment]
@sindresorhus  `observeAll` or `publisherAll` for user-defined keys, should be possible using [Mirror](https://developer.apple.com/documentation/swift/mirror) reflection.

> It should also prevent infinite recursion if you call, for example, `Defaults[.foo] = true` inside the `handler` as that would normally emit an event, which would call it again infinitely. If it doesn't make sense as default, at least there should be an option for this.

I found [this](https://stackoverflow.com/a/17148881). The `observeValue` method would be called once again, but wouldn't propagate changes to later handlers.

**Comment by sindresorhus** [comment]
Thanks for chiming in. That sounds good.
