### ISSUE TITLE
Combine publisher with String? emits "(null)"

### ISSUE THREAD

**Issue by haemi** [sindresorhus/Defaults#35]
when using a key which keeps an optional String like

`static let optionalString = Key<String?>("optionalString", default: nil)`

using defaults directly gives `nil`, as expected:

```
print(Defaults[.optionalString]) // nil
```

but using a Combine publisher emits "(null)" as String:

```
Defaults.publisher(.optionalString).sink { print($0) }.store(in: ...) // KeyChange<Optional<String>>(kind: __C.NSKeyValueChange, indexes: nil, isPrior: false, newValue: Optional("null"), oldValue: nil)
```

I would expect `newValue` to be `nil` as well

**Comment by sindresorhus** [comment]
You need to use `OptionalKey` for optional values. I’m working on a change to allow optional values in `Key`, but I need Swift 5.2 for that.

**Comment by sindresorhus** [comment]
You need to use `OptionalKey` for optional values. I’m working on a change to allow optional values in `Key`, but I need Swift 5.2 for that.
