### ISSUE TITLE
Support `[String: Any]`

### ISSUE THREAD

**Issue by DaFuqtor** [sindresorhus/Defaults#36]
I'm trying to set a Defaults key to observe it later:
```swift
extension Defaults.Keys {
  static let deviceCache = Key<Dictionary>("deviceCache", default: [], suite: UserDefaults(suiteName: "/Library/Preferences/com.apple.Bluetooth")!)
}
```

But after typing this, an error appears and says: `'<T where T : Decodable, T : Encodable> (Defaults.Key<T>.Type) -> (String, T, UserDefaults) -> Defaults.Key<T>' requires that 'Any' conform to 'Encodable'`

What am I doing wrong?

**Comment by sindresorhus** [comment]
The type needs to be `Codable`. The dictionary is only `Codable` if they value type is. `Any` is not `Codable` as it could be anything. The `default` should also be `[:]`.

What is the type of the dictionary values?

**Comment by sindresorhus** [comment]
I think you can make it work by using [`AnyCodable`](https://github.com/Flight-School/AnyCodable) as the value.

I'll look into whether we can add special support for `[String: Any]`.

**Comment by DaFuqtor** [comment]
> I think you can make it work by using [`AnyCodable`](https://github.com/Flight-School/AnyCodable) as the value.

Didn't work :(

**Comment by sindresorhus** [comment]
I tested this now and it does work.

**Comment by sindresorhus** [comment]
> UserDefaults(suiteName: "/Library/Preferences/com.apple.Bluetooth")!

AFAIK, I don't think `suiteNames` accepts a file path.
