### ISSUE TITLE
Combine publisher methods should use `NSObject.KeyValueObservingPublisher`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Defaults#37]
https://developer.apple.com/documentation/objectivec/nsobject/keyvalueobservingpublisher

This should reduce some overhead. Right now, they're based on the [callback API](https://github.com/sindresorhus/Defaults/blob/master/Sources/Defaults/Observation.swift).

---

Eventually (when this package can target macOS 10.15), I imagine the callback APIs like `Defaults.observe()` could be based on the Combine publishers underneath too.

---

// @fredyshox In case you're interested in working on this.

**Comment by fredyshox** [comment]
I was actually thinking about using this, but I wanted the API to be similar to standard `observe:` (same propagated `KeyChange` value). As far as I know, KeyValueObservingPublisher does not give `[NSKeyValueChangeKey: Any]` dictionary.

**Comment by sindresorhus** [comment]
It does support the `old` option though. So there must be a way to get the old value.

By the way, the source for that publisher is now open source: https://github.com/apple/swift/commit/e7cd5ab17f5ce92315f0e23b269628ac2b9369ea

**Comment by sindresorhus** [comment]
A possible solution here: https://stackoverflow.com/questions/60386000/how-to-use-combine-framework-nsobject-keyvalueobservingpublisher

**Comment by sindresorhus** [comment]
Closing as the Combine publishers will eventually be replaced by async stream ones.
