### ISSUE TITLE
Improve stored representation

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Defaults#47]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24113%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/sindresorhus/Defaults/issues/47)

For example, currently, a Codable that is serialized to a `String` is stored as `"foo"` because we serialize it as JSON. It would be nice to make it just `foo` (without the double-quotes).

The following values could be improved when serialized from a Codable:

- String (for example string enum): `"foo"` => `foo`
- Arrays are currently stored as a serialized string in a `String` plist type. We should really use a native plist `Array` type.
- Dictionaries with string keys should also be stored as a native `Dictionary` plist type.

This is a breaking change, so it would have to be an opt-in and we could make it the default in the next major version (with still a way to opt-out so existing projects can upgrade).

---

This is not an easy issue. You are expected to have advanced knowledge of Swift and Codable.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $113.00)

- [<img src='https://avatars.githubusercontent.com/u/170270?v=4' alt='sindresorhus' width=24 height=24> sindresorhus](https://issuehunt.io/u/sindresorhus) ($113.00)

### Submitted pull Requests
- [#57 Add a `Defaults.Serializable` protocol](https://issuehunt.io/r/sindresorhus/Defaults/pull/57)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/Defaults/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by aalenliang** [comment]
Here is my related code, simplified version:
```
extension Defaults.Keys {
    static let deviceId = Key<String?>("SettingsModule.deviceId", default: nil)
}

public static var deviceId: String = {
    let id = Defaults[.deviceId]  // <--- set break point here.
        ?? UIDevice.current.identifierForVendor?.uuidString 
        ?? UUID().uuidString
    
    if Defaults[.deviceId] == nil {
        Defaults[.deviceId] = id
    }

    return id
}
```

in Debug using simulator, iPhone 11 Pro Max (13.6):
```
// Defaults 3.1.1
(lldb) po Defaults[.deviceId]
▿ Optional<String>
  - some : "7B88D8F4-F82C-4413-BE53-D3E26A2F41BC"

// Defaults 4.0.0
(lldb) po Defaults[.deviceId]
▿ Optional<String>
  - some : "\"7B88D8F4-F82C-4413-BE53-D3E26A2F41BC\"" // <--- extra quote mark here.
```

**Comment by sindresorhus** [comment]
@aalenliang I assume you had it as `Key<String?>("SettingsModule.deviceId", default: nil)` even in v3.1.1? Because that syntax was not supported then. It should have been `OptionalKey<String>("SettingsModule.deviceId")`. Since you passed an optional when it was not supported in v3.1.1, it was treated as a non-native value and got quoted even though it shouldn't have. You'll need to do a simple migration yourself. This is not something `Defaults` can handle.

**Comment by aalenliang** [comment]
Yes, I use `Key<Sting?>` since I start using this framework,  which is about a year ago. Since the compiler allows me to do this, I always doing this. 

Ok, I think my issue is irrelevant with this issue, I'll upgrade to the latest version and handle the migration myself.

Thanks!

**Comment by sindresorhus** [comment]
Fixed by #57

**Comment by tonyarnold** [comment]
How do I get the improved representations to work? My enum-based strings are still being saved as `<string>"value"</string>`.

**Comment by tonyarnold** [comment]
Ah, belay that - it's working. I needed to kill a process on my end that was interfering with the updated definition. I _had_ been using `Codable`, but I can see that's unnecessary for simple string-based enums now. Thanks!
