### ISSUE TITLE
Cannot find 'key' in scope

### ISSUE THREAD

**Issue by giovannimariacusaro** [sindresorhus/Defaults#58]
Why [this example](https://github.com/sindresorhus/Defaults#default-values-are-registered-with-userdefaults) doesn't works?

``` swift
extension Defaults.Keys {
	static let isUnicornMode = Key<Bool>("isUnicornMode", default: true)
}
print(UserDefaults.standard.bool(forKey: isUnicornMode.name))  //=> true
```

<img width="1118" alt="Schermata 2020-12-29 alle 13 24 38" src="https://user-images.githubusercontent.com/30832514/103283571-38867980-49d9-11eb-8859-3f9fe5a08fc7.png">

**Comment by sindresorhus** [comment]
This is more of a general Swift question and not related to Defaults.

You need to use the full path, in this case, `Defaults.Keys.isUnicorn`.

**Comment by giovannimariacusaro** [comment]
Sorry, but I don't understand... 
Why general Swift question when I can't call a `let` in a `extension` of **Defaults** following your sample code?
Using `UserDefaults.standard.bool(forKey: "")` why `isUnicornMode.name`, used in example, doesn't works and I need use a different code?

**Comment by sindresorhus** [comment]
Oh, I missed that you were referencing the docs. That's just a typo. Fixed now.

**Comment by giovannimariacusaro** [comment]
Thanks!
