### ISSUE TITLE
Handle key with a dot

### ISSUE THREAD

**Issue by kmalyshev** [sindresorhus/Defaults#59]
Hello,
I am not sure if it's a bug or I am doing something wrong. I have a setting window that users can change settings in. It uses property wrapper '@Default(.key)' for textfields.

However in other piece of code (ViewModel) I am subscribed to changes
```
            Defaults.observe(
                keys: .key1, .key2,
                options: [] // Initial value is not needed.
            ) { [weak self] in
                guard let self = self else { return }
                self.updateValues(array: &self.items)
            }
            .tieToLifetime(of: self)
```
It never gets called even though values are properly saved. I have to manually call update viewModel method after each change. Is it a bug or I'm using the API in a wrong way?

**Comment by sindresorhus** [comment]
I'm using `@Default` without problems in multiple apps.

Are you using `@Default` in a SwiftUI view or a view model? Because it cannot be used in a view model.

I cannot really help much without more info and code.

**Comment by kmalyshev** [comment]
I use @Default in SwiftUI view. 

`@Default(.isOn) var isOn`

and then i have a toggle
`Toggle("Pro mode", isOn: $isOn)`

switching it back and forth doesn't trigger the observation of the same key.

I also tried observing using publisher
`Defaults.publisher(keys: .isOn)`
with sink

**Comment by sindresorhus** [comment]
I'm using both `Defaults.observe` and `Defaults.publisher` in my apps without any problems. It would be helpful if you could provide something I could run so I can debug the issue.

**Comment by sindresorhus** [comment]
> I also tried observing using publisher and '.sink'. Closure after '.sink' never gets triggered.

Maybe try `Defaults.publisher(.isOn)`? (No `keys` parameter) Just to rule out that method being the problem.

**Comment by kmalyshev** [comment]
Found the problem.

`static let proMode = Key<Bool>("name", default: false)`
works well

`static let proMode = Key<Bool>("some.name", default: false)`
doesn't work. If there is a period in the name - observation doesn't happen.

https://github.com/kmalyshev/DefaultsLibTest/

if you remove "." from the name in this file the UI starts working again.

**Comment by sindresorhus** [comment]
That is super weird. I cannot imagine what would cause this to fail.

---

// @hank121314 In case you have any ideas.

**Comment by sindresorhus** [comment]
This *is* a bug in Defaults. We should correctly escape any dot.

**Comment by RoyRao2333** [comment]
> This _is_ a bug in Defaults. We should correctly escape any dot in the observation code path.

Thanks for mentioning this issue! FWIW, it'll be great if this bug can be fixed in the future releases. 🥰

**Comment by sindresorhus** [comment]
Seems like there is no way to escape special characters for an Objective-C key path, so there is really no way to fix this.
