### ISSUE TITLE
v5 release notes draft

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Defaults#68]
### Breaking

- [**Please read the migration guide.**](https://github.com/sindresorhus/Defaults/blob/main/migration.md)
- Removed `NSSecureCodingKey` and `NSSecureCodingOptionalKey`.
	- You can now just use `Key` instead.
- Dropped support for Carthage and CocoaPods.
	- If you use either of these, you can still use Swift Package Manager just for this package.

### Improvements

- Added support for more built-in Swift types.
- Improved the stored representation of many types.
	- For example, `Array` is now stored as a native UserDefaults array instead of being stored as a JSON stringified string. Same with `Set` and `Dictionary`.
- Enums no longer need to be `Codable`. [*(Existing usage requires migration)*](https://github.com/sindresorhus/Defaults/blob/main/migration.md#from-codable-enum-in-defaults-v4-to-rawrepresentable-enum-in-defaults-v5-optional)
- Added support for storing `NSColor` and `UIColor`.
- Added `Defaults.Toggle`.

**Comment by sindresorhus** [comment]
@hank121314 Can you double-check it? Did I forget anything?

I plan to do a beta release soon.

**Comment by hank121314** [comment]
As for `Improvements`, I think v5 also [improve check for natively supported values](https://github.com/sindresorhus/Defaults/issues/51).

Thanks for the beta release!

**Comment by sindresorhus** [comment]
Btw, did you see https://github.com/sindresorhus/Defaults/pull/57#issuecomment-841809919 ?

**Comment by hank121314** [comment]
> Btw, did you see [#57 (comment)](https://github.com/sindresorhus/Defaults/pull/57#issuecomment-841809919) ?

Yes! Thanks for the invitation. https://github.com/sindresorhus/Defaults/pull/57#issuecomment-842190907

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/Defaults/releases/tag/v5.0.0-beta.1
