### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by MatyasKriz** [sindresorhus/Defaults#7]
Hey, this project seems cool! I'm glad you acknowledged SwiftyUserDefaults and stated the difference. Although I would like to use this solution, we use CocoaPods at work, what do you think about adding CocoaPods installation support? 🙂

**Comment by sindresorhus** [comment]
Too intrusive and buggy.

**Comment by sindresorhus** [comment]
Closing, but still happy to receive a good PR.

**Comment by sindresorhus** [comment]
Now available on CocoaPods: https://cocoapods.org/pods/Defaults
