### ISSUE TITLE
v5 feedback

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Defaults#70]
https://github.com/sindresorhus/Defaults/releases/tag/v5.0.0-beta.1

This is an open space to provide feedback about the v5 release.

**Comment by mattgreen** [comment]
Looks solid. I'm a bit hesitant to upgrade because of the necessity of migrating and the potential for issues around that going wrong. However don't take my conservatism as a slight against the changes.

**Comment by sindresorhus** [comment]
v5 is now out https://github.com/sindresorhus/Defaults/releases/tag/v5.0.0
