### ISSUE TITLE
Support `NSUbiquitousKeyValueStore`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Defaults#75]
https://developer.apple.com/documentation/foundation/nsubiquitouskeyvaluestore

It would be nice to be able to mark keys as being sync'able and have them be automatically synced with iCloud. Syncing settings/data is a very common need, but it's currently difficult to get right. We could make it super easy.

`UserDefaults` would still be the main storage, as per Apple docs:

> Avoid using this class for data that is essential to your app’s behavior when offline; instead, store such data directly into the local user defaults database.

---

We could take some inspiration from https://github.com/ArtSabintsev/Zephyr:

```swift
// Add keys to be automatically synced.
Defaults.iCloud.add(.foo, .bar)

// Remove keys to be automatically synced.
Defaults.iCloud.remove(.foo)

// Lists the synced keys.
Defaults.iCloud.keys

// Force sync all added keys.
Defaults.iCloud.sync()
```

We could also make a key syncable by default:

```swift
extension Defaults.Keys {
	static let quality = Key<Double>("quality", default: 0.8, iCloud: true)

}
```

---

@hank121314 Thoughts on the idea and the API?

**Comment by sindresorhus** [comment]
>  think we might also need to add an observation for NSUbiquitousKeyValueStore.didChangeExternallyNotification.

I was thinking that we handle that internally. The user would just use `Defaults.publisher`, which would also be triggered by that notification.

The point of this feature is to handle the sync automatically. All the user has to do is to provide the set of keys that should be synced. Everything else is just normal `Defaults` usage.

> Should we also do this in Defaults?

Yeah, I think so.

**Comment by hank121314** [comment]
> I was thinking that we handle that internally. The user would just use Defaults.publisher, which would also be triggered by that notification.

Got it! Maybe we can add a new `ObservationOption` for this notification?
It will be useful for users to recognize this notification.

For example:
```swift
Defaults.publisher(.key, options: [.iCloud or .sync])
```

**Comment by sindresorhus** [comment]
> Maybe we can add a new ObservationOption for this notification?

What's the use-case?

**Comment by hank121314** [comment]
> What's the use-case?

I am not sure what kinds of use-case honestly.
But this will be more convenient for those who only want to listen to the  `NSUbiquitousKeyValueStore.didChangeExternallyNotification` notification.

**Comment by sindresorhus** [comment]
Yes, but I'm curious why people would need to listen to `NSUbiquitousKeyValueStore.didChangeExternallyNotification`, since with my proposed solution, that event is just handled for them, so they don't need to care.

I feel like we're maybe talking past each other. With my solution, Defaults would listen to `NSUbiquitousKeyValueStore.didChangeExternallyNotification` internally, fetch the changes, merge them in, and then trigger a normal defaults update. From the user's perspective, they just use Defaults like they always have, but they now have full syncing included for free without any extra work, other than registering the keys they want synced.

**Comment by hank121314** [comment]
> Defaults would listen to NSUbiquitousKeyValueStore.didChangeExternallyNotification internally, fetch the changes, merge them in, and then trigger a normal defaults update. From the user's perspective, they just use Defaults like they always have, but they now have full syncing included for free without any extra work, other than registering the keys they want synced.

Yeah! That's the main feature. 
But I would like to let users know who make the changes.
With `Defaults.publisher(.key, options: [.iCloud or .sync])` they will be able to know this change was made by remote synchroization.

**Comment by sindresorhus** [comment]
I think a property on the `Observation` object would be better. Maybe `.isSyncUpdate`. But I would wait until someone has an actual need for this. It would be easier to design a solution around an actual need than trying to anticipate what users will need.

**Comment by hank121314** [comment]
> But I would wait until someone has an actual need for this.

Yeah! Let's just keep an open mind to this additional feature.

>  It would be easier to design a solution around an actual need than trying to anticipate what users will need.

That's true 👍. Learn a lot from it 😃 !

**Comment by Pomanks** [comment]
It was missing by the time I needed it so I implemented something on my own (locally) for now but it's not as deeply integrated as what you plan on adding and relies on me checking for `NSUbiquitousKeyValueStore.didChangeExternallyNotification` and updating the values then so… please let me know if I can help! 😄

**Comment by sindresorhus** [comment]
This is now available for testing: https://github.com/sindresorhus/Defaults/releases/tag/v9.0.0-beta.1

// @Pomanks @Kinark @seungwoochoe @Frostplexx @arekf

**Comment by sindresorhus** [comment]
It's officially out now: https://github.com/sindresorhus/Defaults/releases/tag/9.0.0
