### ISSUE TITLE
Is it possible to support SwiftUI Color ?

### ISSUE THREAD

**Issue by L1cardo** [sindresorhus/Defaults#78]
Defaults now supports `NSColor` and `UIColor`, so I think is it possible to support SwiftUI Color since we can create a Color view using
```swift
Color(NSColor.systemRed)
```

So I did this:

```swift
extension Defaults.Keys {
	static let color = Key<NSColor>("color", default: .systemRed)
}

struct Example: View {
	@Default(.color) var color
	@State var pickerColor = Color(Defaults[.color])
	
	var body: some View {
	  ColorPicker("", selection: $pickerColor, supportsOpacity: false)
		  .onChange(of: pickerColor) { color in
			  self.color = NSColor(color)
		  }
	}
}
```

Although there is some don't-know-why weirdness, it somehow did the trick.
I am not a Swift pro, but it made the things work.

So I wonder if there is some other better ways to do this?

**Comment by sindresorhus** [comment]
Yeah, we can support `Color`, using:

- https://developer.apple.com/documentation/appkit/nscolor/3554622-init
- https://developer.apple.com/documentation/swiftui/color/init(nscolor:)
- https://developer.apple.com/documentation/uikit/uicolor/3550899-init
- https://developer.apple.com/documentation/swiftui/color/init(uicolor:)

**Comment by sindresorhus** [comment]
Your current approach is fine, but the `ColorPicker` will not reflect the color change if `var color` changes. An alternative solution is to create a new `Binding` that converts between `Color` and `NSColor`.

**Comment by hank121314** [comment]
When I was trying to implement this feature I encounter some swift compiler issues 😢 .
Luckily, I tried to compile with Xcode 13.0.0-Beta.3 it works.
After Xcode 13 and swift 5.5 are released, these issues might resolve.

Btw, Since `NSColor.init(_ color: Color)` is only available for macOS 11+.
`Defaults` SwiftUI Color support will also be available for macOS 11+.
