### ISSUE TITLE
Xcode 13 archive error

### ISSUE THREAD

**Issue by automactic** [sindresorhus/Defaults#81]
Hey, thanks for creating and maintaining this awesome package. Using the GM version of Xcode 13 (13A233), I can compile and run my app against the iOS 15 SDK just fine, but encountering errors when archiving the app. See screenshot below for detail.

It seems rather strange... Maybe we need to do `canImport(Combine) && canImport(SwiftUI)` at the top of `SwiftUI.swift`? I got no idea

<img width="312" alt="Screen Shot 2021-09-14 at 10 39 42 PM" src="https://user-images.githubusercontent.com/8294252/133361461-43702563-a633-4281-8446-6bfdbfac0a3d.png">

**Comment by quantamrhino** [comment]
Same problem here :-(

**Comment by sindresorhus** [comment]
I just tried archiving with the latest Xcode 13 RC on multiple projects and it works fine for me. Try cleaning your build folder and resetting the package cache ("File" => "Packages").

Are you using the latest version of `Defaults`?

**Comment by quantamrhino** [comment]
version 4 of defaults-  just realized there's a steep migration step to go to 5 (i'll do that soon - need testing time). 
this was on a clean build. i'll try reseting the cache and report back.

**Comment by quantamrhino** [comment]
No luck. did a package cache reset, cleaned build folder and archived again. Same errors. :-(

**Comment by RoyRao2333** [comment]
> I just tried archiving with the latest Xcode 13 RC on multiple projects and it works fine for me. Try cleaning your build folder and resetting the package cache ("File" => "Packages").
> 
> Are you using the latest version of `Defaults`?

Hi, I've reset the package cache and I've been using Defaults 5.0.0 all along. Just upgraded to Xcode 13 RC this afternoon and suddenly these errors came up. Any solutions? :)

**Comment by xiao99xiao** [comment]
First, this is caused by a known issue in Xcode 13. You can read more details about it in[ its release notes here](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes)(Search for 74120874)

The suggested workaround is lifting the deploy target up to iOS_12, which happens to be done already on main branch but not included in 5.0 release, which explains why @sindresorhus doesn't meet the issue while others did.

**Comment by RoyRao2333** [comment]
> This is caused by a known issue in Xcode 13 throughout Beta and RC. You can read more details about it in[ its release notes here](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes)(Search for 74120874)
> 
> It only happens in building for armv7 devices or archiving, which may possibly explain why @sindresorhus doesn't meet the issue while others did.
> 
> The suggested workaround is lifting the deploy target up to iOS_12.

My deployment target is iOS13 but you're right.

If your built device is something like __Any iOS Device (arm64)__, you'll meet these bugs for no reason. The solution for now is to select a simulator other than an __arm64__ device in build-time. Or, you can just plug your iPhone in and debug on your own devices. 

Hope this will help anybody.

**Comment by RoyRao2333** [comment]
My deployment target is iOS13 but @xiao99xiao is right.

If your built device is something like Any iOS Device (arm64), you'll meet these bugs for no reason. The solution for now is to select a simulator other than an arm64 device in build-time. Or, you can just plug your iPhone in and debug on your own devices.

Hope this will help anybody.

**Comment by quantamrhino** [comment]
For me its the archive. my target ios is 14. i can't upload a build to testflight because of this.

**Comment by automactic** [comment]
Yeah the problem is not build, it is archiving. Even if I tell Xcode to explicitly exclude armv7, I am still having this issue. (my deployment target is iOS 13)

@sindresorhus Does any project you test with use swiftui?

<img width="597" alt="Screen Shot 2021-09-15 at 7 42 53 AM" src="https://user-images.githubusercontent.com/8294252/133427128-fc0cd1c7-1269-4010-90f8-0153d799669e.png">

**Comment by automactic** [comment]
> The suggested workaround is lifting the deploy target up to iOS_12.

Ohhh, upon re-reading the release note, I realized the dependency needs to (temporarily) raise the deploy target to `v12`. I though my app needs to make this change.

I [forked](https://github.com/automactic/Defaults/tree/xcode13) this library, made that single change and was able to archive my app.

**Comment by pwightman** [comment]
I'm also having this error, and the fix does appear to be to update Defaults' deploy target to v12 in Package.swift. I'd like to not fork this, and would also prefer not to have to upgrade to v5 (still on v4) just to get this fix...anyone have a workaround? May just need to create a fork in the meantime. 

![image](https://user-images.githubusercontent.com/838674/133682380-6d496024-5a06-4f18-a19f-e21fe92c9e39.png)

**Comment by igoriols** [comment]
> > The suggested workaround is lifting the deploy target up to iOS_12.
> 
> Ohhh, upon re-reading the release note, I realized the dependency needs to (temporarily) raise the deploy target to `v12`. I though my app needs to make this change.
> 
> I [forked](https://github.com/automactic/Defaults/tree/xcode13) this library, made that single change and was able to archive my app.

I tried to do the same thing, but I'm not able to import the dependency from my fork using Swift Package Manager. It always targeting the original repo.
Hi, @automactic how did you import the library from your fork?
Can you help me?

**Comment by L1cardo** [comment]
> > The suggested workaround is lifting the deploy target up to iOS_12.
> 
> Ohhh, upon re-reading the release note, I realized the dependency needs to (temporarily) raise the deploy target to `v12`. I though my app needs to make this change.
> 
> I [forked](https://github.com/automactic/Defaults/tree/xcode13?rgh-link-date=2021-09-15T22%3A17%3A25Z) this library, made that single change and was able to archive my app.

I did this and new problems came :(

<img width="443" alt="image" src="https://user-images.githubusercontent.com/33802186/134544220-79857b08-726b-4e52-9d62-9dd665146ceb.png">

**Comment by pwightman** [comment]
FWIW, I forked and branched from the most recent 4.X.X commit, change to `v12` and it did work.

**Comment by pwightman** [comment]
I had to remove the original Defaults package, and then added it via Xcode 13's package thing, pasting my URL into the textbox in the top-right corner and adding the package that showed up. I then specified the branch name I had made.

**Comment by JustinFincher** [comment]
> > > The suggested workaround is lifting the deploy target up to iOS_12.
> > 
> > 
> > Ohhh, upon re-reading the release note, I realized the dependency needs to (temporarily) raise the deploy target to `v12`. I though my app needs to make this change.
> > I [forked](https://github.com/automactic/Defaults/tree/xcode13) this library, made that single change and was able to archive my app.
> 
> I tried to do the same thing, but I'm not able to import the dependency from my fork using Swift Package Manager. It always targeting the original repo.
> Hi, @automactic how did you import the library from your fork?
> Can you help me?

@igoriols I was able to resolve the issue by removing the previous Default repo link from "Recently Used" in the first place and then paste the [one](https://github.com/automactic/Defaults/) from @automactic. It should be pointing to the new one after that

![image](https://user-images.githubusercontent.com/8359912/134759983-815e338e-77b6-43b4-858c-f2f4724fc8bc.png)

**Comment by automactic** [comment]
@igoriols Hey sorry I forgot to reply to your question, @JustinFincher got the right answer
