### ISSUE TITLE
Cannot find type 'DynamicProperty' in scope , xcode 13 error

### ISSUE THREAD

**Issue by iZeDeveloper** [sindresorhus/Defaults#85]
Hi, i am not sure why but this error is bumping up everytime i am trying to make archive, can you please guide what is wrong.  

file name : SwiftUI.swift
uses combine framework. 

Looking for solution. 
thanks

**Comment by sindresorhus** [comment]
Make sure you're using the latest version. This should have been fixed there.

**Comment by sindresorhus** [comment]
You should probably also read release notes when upgrading: https://github.com/sindresorhus/Defaults/releases/tag/v5.0.0

**Comment by iZeDeveloper** [comment]
i am sorry if i offend you but i just integrated latest version for this pod, i am not using this in my project, the only thing i added is pod. release notes would help if i am using within project.
