### ISSUE TITLE
Functions will be called immediately after adding observers

### ISSUE THREAD

**Issue by RoyRao2333** [sindresorhus/Defaults#86]
Here's the thing: I recently discovered that when I add an observer to a key, the callback will be invoked immediately.
Details as below in my ViewController:

![image](https://user-images.githubusercontent.com/31413093/140041825-95f4e7c6-fba6-4bd8-95bc-778cebb44447.png)

My ```func didResetJCState(_:)``` will be called whenever the view is presented. Actually, I just want this function to be called only ```.sessionURL``` is changed. I don't know if this is a feature of your framework or anything...

Any advice would be great! :)

**Comment by sindresorhus** [comment]
That is the documented behavior: https://github.com/sindresorhus/Defaults#defaultsobserve

You can use `Defaults.observe(.sessionURL, options: [.new])` if you don't want this.

**Comment by RoyRao2333** [comment]
> That is the documented behavior: https://github.com/sindresorhus/Defaults#defaultsobserve
> 
> You can use `Defaults.observe(.sessionURL, options: [.new])` if you don't want this.

Thank you so much for your reply!

**Comment by RoyRao2333** [comment]
> That is the documented behavior: https://github.com/sindresorhus/Defaults#defaultsobserve
> 
> You can use `Defaults.observe(.sessionURL, options: [.new])` if you don't want this.

Sorry to bother you again but I found that there's no ```.new``` in options:

![image](https://user-images.githubusercontent.com/31413093/140049321-ce880a38-40b8-44e0-91a4-943d61f73ae9.png)

Any ideas? 😓

**Comment by sindresorhus** [comment]
Ah, yeah. My mistake, should be:

```swift
Defaults.observe(.sessionURL, options: [])
```

**Comment by RoyRao2333** [comment]
> Ah, yeah. My mistake, should be:
> 
> ```swift
> Defaults.observe(.sessionURL, options: [])
> ```

Thanks! That works perfectly!

**Comment by RoyRao2333** [comment]
@sindresorhus 
And I would like to know that if I reassign a ```myValue``` to ```Defaults[.myValue]``` which they are identical (for example, ```myValue``` and ```Defaults[.myValue]``` are both equal to 100), could this trigger the callback in ```Defaults.observe```? 

Thanks!

**Comment by sindresorhus** [comment]
Yes, there's no deduplication going on. It will trigger for every assignment.

**Comment by RoyRao2333** [comment]
> Yes, there's no deduplication going on. It will trigger for every assignment.

Thank you so much for your time!
