### ISSUE TITLE
Switch between x86_64 and arm64 issue?

### ISSUE THREAD

**Issue by RoyRao2333** [sindresorhus/Defaults#88]
Hi, I just came across a problem a few days ago when I was developing a macOS project: If I build universally in debug, this framework would get errors like ```Requires arm64 ... found x86_64 instead.```.

![image](https://user-images.githubusercontent.com/31413093/144998541-9a767055-c78e-4b80-9d9c-fada7212ea41.png)

I'm using a x86 iMac in my office, and a M1 Pro (arm64) at home, don't know if this is the cause... It's just so weird that Defaults is the only framework that's complaining about this, and other frameworks seems fine...

<img width="1250" alt="Screen Shot 2021-12-07 at 17 20 12" src="https://user-images.githubusercontent.com/31413093/145001876-b9689660-f1fa-4596-88af-7331e5791c37.png">

Any thoughts? :)

**Comment by sindresorhus** [comment]
I don't think this is a problem with this package. We're not doing anything special here. Just a standard package: https://github.com/sindresorhus/Defaults/blob/main/Package.swift

https://stackoverflow.com/questions/64026065/xcode-12-issue-could-not-find-module-frameworkname-for-target-arm64-apple-i
