### ISSUE TITLE
Binding of array item

### ISSUE THREAD

**Issue by Vincz** [sindresorhus/Defaults#94]
Hi guys. I've been using this library to cleanup my codebase but I'm stuck with a little problem. Sorry if my question is stupid, I'm just starting with Swift and there is quite a lot to process.

My settings looks like this:
```swift
class Entry: Codable, Identifiable, Defaults.Serializable {
    var id: String
    var displayLogo: Bool = true
}
extension Defaults.Keys {
    static let entries = Key<[Entry]>("entries", default: [])
}
```

in a View, I'm looping through the entries like this and display a view for each entry.
```swift
struct EntryView: View {
      @State var entry: Entry

      var body: some View {
            Text("Inside entry \(entry.id)")
             Toggle("Display logo?", isOn: $entry.displayLogo) // <-- This 
       }
}

struct EntriesView: View {
    @Default(.entries) var entries : [Entry];
    
    var body: some View {
        HStack(spacing: 10) {
            ForEach(entries) { entry in
                 EntryView(entry: entry)
            }
        }
     }
```

The binding `$entry.displayLogo` doesn't work. I'd like to be able to update the configuration for a particular entry from inside the view (ie. Update the value of `displayLogo`).
Any idea how I could achieve this behavior? I know I could pass an index through the sub views and use something like `entries[entryIndex].displayLogo` but it doesn't seem very clean.
Thanks

**Comment by sindresorhus** [comment]
Your question is not related to `Defaults`, but I will answer it.

You need to pass the `Binding` to the `EntryView`. Notice the `$` in `ForEach`. That new in Xcode 13.2 or something.

```swift
struct EntryView: View {
      @Binding var entry: Entry

      var body: some View {
            Text("Inside entry \(entry.id)")
             Toggle("Display logo?", isOn: $entry.displayLogo)
       }
}

struct EntriesView: View {
    @Default(.entries) var entries

    var body: some View {
        HStack(spacing: 10) {
            ForEach($entries) { entry in
                 EntryView(entry: entry)
            }
        }
     }
}
```

**Comment by sindresorhus** [comment]
Unrelated, but `Entry` should be a struct. And you don't need the type annotation on `@Default`.

And I would recommend using `UUID` as `id`.

**Comment by Vincz** [comment]
Thank you for your help, you saved me a lot of time.
Allow me to buy you a couple of beers.
