### ISSUE TITLE
Color space is not preserved for `Color` type on iOS

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Defaults#97]
It is however preserved for `UIColor`.

Report: https://twitter.com/jordibruin/status/1516728958695354369

I have added some tests and this one fails on iOS: https://github.com/sindresorhus/Defaults/commit/3535f3d088113cf24705014eec6a17f0fd73237f#diff-d780be73215173c5c7564ee04feb252d30d24c3842b4d9f4aada400be8f37352R21

This seems to be a bug in when SwiftUI translates between `UIColor` and `Color`?

**Comment by sindresorhus** [comment]
@hank121314 Any ideas?

**Comment by hank121314** [comment]
The behavior of `UIColor` seems weird.

I had tested with the following code

```swift
let uiColor = UIColor(displayP3Red: 1, green: 0.3, blue: 0.7, alpha: 1)
print(uiColor.cgColor.colorSpace!) // sRGB
let p3 = CGColorSpace(name: CGColorSpace.displayP3)!
let cgColor = uiColor.cgColor.converted(to: p3, intent: .defaultIntent, options: nil)!
print(cgColor.colorSpace!) // P3
let fixture = UIColor(cgColor: cgColor)
print(fixture.cgColor.colorSpace!) // P3
```

Even if we create `UIColor` with `init(displayP3Red:green:blue:alpha:)` the color space is still `sRGB`.
And also when using `NSSecureCodingBridge` to serialize and deserialize `UIColor`, color space will also return to `sRGB`.
There is need for further investigation 🤓 .

**Comment by sindresorhus** [comment]
`UIColor` always converts to and stores the color internally as "extended sRGB", but I had thought that it would store the original color space.

Maybe we could subclass `UIColor` and add a color space property. I'm not sure whether that would be archived or not though.

**Comment by hank121314** [comment]
It is really hard to add a color space property in `UIColor` subclass. Reference: [You Can't Subclass UIColor](https://cjwirth.com/tech/you-cant-subclass-uicolor).
Is it acceptable to create a class like this?

```swift
public class DefaultsUIColor {
	private var _colorSpace: Color.RGBColorSpace = .sRGB
	public var colorSpace: Color.RGBColorSpace { return _colorSpace }
	
	public let color: UIColor
	public init(_ colorSpace: Color.RGBColorSpace, red: Double, green: Double, blue: Double, alpha: Double)
}
```

**Comment by sindresorhus** [comment]
Actually, the issue is not with `UIColor`. `UIColor` does not preserve the color space, which is fine. `Defaults` should not try to work around that. The color is correctly preserved.

The problem is that a `SwiftUI.Color` in contrast to `UIColor` does store the color space, but it's not preserved because we convert to `UIColor`. So I think the solution would be to use your above wrapper as internal storage when storing `SwiftUI.Color`.

**Comment by sindresorhus** [comment]
@hank121314 That sound like a good solution. 👍

**Comment by jordibruin** [comment]
Just wanted to thank @hank121314 and @sindresorhus again for fixing this 🙂
