### ISSUE TITLE
Support `ClosedRange` and `Range`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Defaults#98]
I think they should just serialize into an array with two elements: `.lowerBound` and `.upperBound`.

@hank121314 Thoughts?

**Comment by hank121314** [comment]
Yes! swift also only encode these two elements. 
I think we might also support any `Bound` that conforms to `Defaults.Serializable`?

Reference: https://github.com/apple/swift/blob/223d73cc470d2395b3d55d07eaf6866e7f6171f9/stdlib/public/core/ClosedRange.swift#L495-L501

**Comment by sindresorhus** [comment]
> I think we might also support any Bound that conforms to Defaults.Serializable?

👍
